SystemOrganization addCategory: #'Thermite-Card'!
SystemOrganization addCategory: #'Thermite-Card-CodeAnalysis'!
SystemOrganization addCategory: #'Thermite-Card-CodeAnalysis-Pharo'!
SystemOrganization addCategory: #'Thermite-Card-CodeAnalysis-Python'!
SystemOrganization addCategory: #'Thermite-Card-CodeAnalysis-Similarity'!
SystemOrganization addCategory: #'Thermite-Card-Menu'!
SystemOrganization addCategory: #'Thermite-Card-Tests'!
