initialization
originalPalette
	textColor := Color veryDarkGray.
	importantTextColor := Color black.
	
	viewBackground := Color white.
	visitCardBackground := Color veryVeryLightGray lighter.
	metricPlotBackground := Color veryLightGray muchLighter.
	filesBackground := Color veryLightGray lighter.
	packageBackground := Color veryLightGray.
	
	unchangedColor := Color lightGray.
	leafUnchangedColor := unchangedColor muchLighter.
	additionsColor := Color green.
	deletionsColor := Color red.
	modifiedColor := Color yellow.
	movementColor := Color blue.
	
	mergeablePullRequestColor := Color green.
	unmergablePullRequestColor := Color orange.
	mergeabilityUnknownColor := Color darkGray.

	testFileColor := Color green muchDarker.
	normalFileColor := Color gray.
	
	classMovementRefactorInteriorColor := Color blue lighter lighter.
	classInteriorColor := Color lightGray muchLighter.
	classHierarchyUnchangedColor := Color blue.
	
	testNodeBorderdColor := testFileColor.
	normalNodeBorderColor := Color black.
